### ISSUE TITLE
Stonecutter is renamed in English?

### ISSUE THREAD

**Issue by whatusernamenottopick** [mrh0/buildersaddition#17]
Hey, apparently stonecutter is named "Bench Saw" in US English, with this mod installed. I'm not sure whether this is a bug or a feature?
![zxcvbnm](https://user-images.githubusercontent.com/35191521/102713665-31b98180-42ca-11eb-8ce4-b92890b95048.png)

**Comment by mrh0** [comment]
Yes, this is intentional since you can use wood it with my mod, I thought it would make more sense to name it Bench Saw.

**Comment by whatusernamenottopick** [comment]
May I suggest a config option to enable/disable this?

**Comment by yurifel** [comment]
Seconding this.  I understand the logic, but practically it just makes it harder to find (via JEI or the creative menu).  It seems particularly confusing for people new to 1.14+, who might only be vaguely aware that the stonecutter even exists.

As an alternative to renaming (or a config option), you could also consider a separate wood-cutting block (similar to the ones added by Charm and Druidcraft).  Or, even more ideally, it would be amazing to see compatibility with the aforementioned mods:  if Charm is installed, use the woodcutter, otherwise use the stonecutter.

**Comment by HopsandBarley** [comment]
Third.  Would like this to be configurable also.
